export type CountryOption = {
  code: string
  label: string
}

export const COUNTRY_OPTIONS: ReadonlyArray<CountryOption> = [
  { code: 'AF', label: 'Afghanistan' },
  { code: 'AL', label: 'Albania' },
  { code: 'DZ', label: 'Algeria' },
  { code: 'AD', label: 'Andorra' },
  { code: 'AO', label: 'Angola' },
  { code: 'AG', label: 'Antigua and Barbuda' },
  { code: 'AR', label: 'Argentina' },
  { code: 'AM', label: 'Armenia' },
  { code: 'AU', label: 'Australia' },
  { code: 'AT', label: 'Austria' },
  { code: 'AZ', label: 'Azerbaijan' },
  { code: 'BS', label: 'Bahamas' },
  { code: 'BH', label: 'Bahrain' },
  { code: 'BD', label: 'Bangladesh' },
  { code: 'BB', label: 'Barbados' },
  { code: 'BY', label: 'Belarus' },
  { code: 'BE', label: 'Belgium' },
  { code: 'BZ', label: 'Belize' },
  { code: 'BJ', label: 'Benin' },
  { code: 'BT', label: 'Bhutan' },
  { code: 'BO', label: 'Bolivia' },
  { code: 'BA', label: 'Bosnia and Herzegovina' },
  { code: 'BW', label: 'Botswana' },
  { code: 'BR', label: 'Brazil' },
  { code: 'BN', label: 'Brunei' },
  { code: 'BG', label: 'Bulgaria' },
  { code: 'BF', label: 'Burkina Faso' },
  { code: 'BI', label: 'Burundi' },
  { code: 'CV', label: 'Cabo Verde' },
  { code: 'KH', label: 'Cambodia' },
  { code: 'CM', label: 'Cameroon' },
  { code: 'CA', label: 'Canada' },
  { code: 'CF', label: 'Central African Republic' },
  { code: 'TD', label: 'Chad' },
  { code: 'CL', label: 'Chile' },
  { code: 'CN', label: 'China' },
  { code: 'HK', label: 'Hong Kong' },
  { code: 'MO', label: 'Macau' },
  { code: 'CO', label: 'Colombia' },
  { code: 'KM', label: 'Comoros' },
  { code: 'CD', label: 'Congo (Democratic Republic)' },
  { code: 'CG', label: 'Congo (Republic)' },
  { code: 'CR', label: 'Costa Rica' },
  { code: 'CI', label: "Côte d’Ivoire" },
  { code: 'HR', label: 'Croatia' },
  { code: 'CU', label: 'Cuba' },
  { code: 'CY', label: 'Cyprus' },
  { code: 'CZ', label: 'Czechia' },
  { code: 'DK', label: 'Denmark' },
  { code: 'DJ', label: 'Djibouti' },
  { code: 'DM', label: 'Dominica' },
  { code: 'DO', label: 'Dominican Republic' },
  { code: 'EC', label: 'Ecuador' },
  { code: 'EG', label: 'Egypt' },
  { code: 'SV', label: 'El Salvador' },
  { code: 'GQ', label: 'Equatorial Guinea' },
  { code: 'ER', label: 'Eritrea' },
  { code: 'EE', label: 'Estonia' },
  { code: 'SZ', label: 'Eswatini' },
  { code: 'ET', label: 'Ethiopia' },
  { code: 'FJ', label: 'Fiji' },
  { code: 'FI', label: 'Finland' },
  { code: 'FR', label: 'France' },
  { code: 'GA', label: 'Gabon' },
  { code: 'GM', label: 'Gambia' },
  { code: 'GE', label: 'Georgia' },
  { code: 'DE', label: 'Germany' },
  { code: 'GH', label: 'Ghana' },
  { code: 'GR', label: 'Greece' },
  { code: 'GD', label: 'Grenada' },
  { code: 'GT', label: 'Guatemala' },
  { code: 'GN', label: 'Guinea' },
  { code: 'GW', label: 'Guinea-Bissau' },
  { code: 'GY', label: 'Guyana' },
  { code: 'HT', label: 'Haiti' },
  { code: 'HN', label: 'Honduras' },
  { code: 'HU', label: 'Hungary' },
  { code: 'IS', label: 'Iceland' },
  { code: 'IN', label: 'India' },
  { code: 'ID', label: 'Indonesia' },
  { code: 'IR', label: 'Iran' },
  { code: 'IQ', label: 'Iraq' },
  { code: 'IE', label: 'Ireland' },
  { code: 'IL', label: 'Israel' },
  { code: 'IT', label: 'Italy' },
  { code: 'JM', label: 'Jamaica' },
  { code: 'JP', label: 'Japan' },
  { code: 'JO', label: 'Jordan' },
  { code: 'KZ', label: 'Kazakhstan' },
  { code: 'KE', label: 'Kenya' },
  { code: 'KI', label: 'Kiribati' },
  { code: 'KW', label: 'Kuwait' },
  { code: 'KG', label: 'Kyrgyzstan' },
  { code: 'LA', label: 'Laos' },
  { code: 'LV', label: 'Latvia' },
  { code: 'LB', label: 'Lebanon' },
  { code: 'LS', label: 'Lesotho' },
  { code: 'LR', label: 'Liberia' },
  { code: 'LY', label: 'Libya' },
  { code: 'LI', label: 'Liechtenstein' },
  { code: 'LT', label: 'Lithuania' },
  { code: 'LU', label: 'Luxembourg' },
  { code: 'MG', label: 'Madagascar' },
  { code: 'MW', label: 'Malawi' },
  { code: 'MY', label: 'Malaysia' },
  { code: 'MV', label: 'Maldives' },
  { code: 'ML', label: 'Mali' },
  { code: 'MT', label: 'Malta' },
  { code: 'MH', label: 'Marshall Islands' },
  { code: 'MR', label: 'Mauritania' },
  { code: 'MU', label: 'Mauritius' },
  { code: 'MX', label: 'Mexico' },
  { code: 'FM', label: 'Micronesia' },
  { code: 'MD', label: 'Moldova' },
  { code: 'MC', label: 'Monaco' },
  { code: 'MN', label: 'Mongolia' },
  { code: 'ME', label: 'Montenegro' },
  { code: 'MA', label: 'Morocco' },
  { code: 'MZ', label: 'Mozambique' },
  { code: 'MM', label: 'Myanmar' },
  { code: 'NA', label: 'Namibia' },
  { code: 'NR', label: 'Nauru' },
  { code: 'NP', label: 'Nepal' },
  { code: 'NL', label: 'Netherlands' },
  { code: 'NZ', label: 'New Zealand' },
  { code: 'NI', label: 'Nicaragua' },
  { code: 'NE', label: 'Niger' },
  { code: 'NG', label: 'Nigeria' },
  { code: 'KP', label: 'North Korea' },
  { code: 'MK', label: 'North Macedonia' },
  { code: 'NO', label: 'Norway' },
  { code: 'OM', label: 'Oman' },
  { code: 'PK', label: 'Pakistan' },
  { code: 'PW', label: 'Palau' },
  { code: 'PS', label: 'Palestine' },
  { code: 'PA', label: 'Panama' },
  { code: 'PG', label: 'Papua New Guinea' },
  { code: 'PY', label: 'Paraguay' },
  { code: 'PE', label: 'Peru' },
  { code: 'PH', label: 'Philippines' },
  { code: 'PL', label: 'Poland' },
  { code: 'PT', label: 'Portugal' },
  { code: 'QA', label: 'Qatar' },
  { code: 'RO', label: 'Romania' },
  { code: 'RU', label: 'Russia' },
  { code: 'RW', label: 'Rwanda' },
  { code: 'KN', label: 'Saint Kitts and Nevis' },
  { code: 'LC', label: 'Saint Lucia' },
  { code: 'VC', label: 'Saint Vincent and the Grenadines' },
  { code: 'WS', label: 'Samoa' },
  { code: 'SM', label: 'San Marino' },
  { code: 'ST', label: 'São Tomé and Príncipe' },
  { code: 'SA', label: 'Saudi Arabia' },
  { code: 'SN', label: 'Senegal' },
  { code: 'RS', label: 'Serbia' },
  { code: 'SC', label: 'Seychelles' },
  { code: 'SL', label: 'Sierra Leone' },
  { code: 'SG', label: 'Singapore' },
  { code: 'SK', label: 'Slovakia' },
  { code: 'SI', label: 'Slovenia' },
  { code: 'SB', label: 'Solomon Islands' },
  { code: 'SO', label: 'Somalia' },
  { code: 'ZA', label: 'South Africa' },
  { code: 'KR', label: 'South Korea' },
  { code: 'SS', label: 'South Sudan' },
  { code: 'ES', label: 'Spain' },
  { code: 'LK', label: 'Sri Lanka' },
  { code: 'SD', label: 'Sudan' },
  { code: 'SR', label: 'Suriname' },
  { code: 'SE', label: 'Sweden' },
  { code: 'CH', label: 'Switzerland' },
  { code: 'SY', label: 'Syria' },
  { code: 'TJ', label: 'Tajikistan' },
  { code: 'TZ', label: 'Tanzania' },
  { code: 'TH', label: 'Thailand' },
  { code: 'TW', label: 'Taiwan' },
  { code: 'TL', label: 'Timor-Leste' },
  { code: 'TG', label: 'Togo' },
  { code: 'TO', label: 'Tonga' },
  { code: 'TT', label: 'Trinidad and Tobago' },
  { code: 'TN', label: 'Tunisia' },
  { code: 'TR', label: 'Turkey' },
  { code: 'TM', label: 'Turkmenistan' },
  { code: 'TV', label: 'Tuvalu' },
  { code: 'UG', label: 'Uganda' },
  { code: 'UA', label: 'Ukraine' },
  { code: 'AE', label: 'United Arab Emirates' },
  { code: 'GB', label: 'United Kingdom' },
  { code: 'US', label: 'United States' },
  { code: 'UY', label: 'Uruguay' },
  { code: 'UZ', label: 'Uzbekistan' },
  { code: 'XK', label: 'Kosovo' },
  { code: 'VU', label: 'Vanuatu' },
  { code: 'VA', label: 'Vatican City' },
  { code: 'VE', label: 'Venezuela' },
  { code: 'VN', label: 'Vietnam' },
  { code: 'YE', label: 'Yemen' },
  { code: 'ZM', label: 'Zambia' },
  { code: 'ZW', label: 'Zimbabwe' },
] as const

function normalizeValue(value: string) {
  return value
    .trim()
    .normalize('NFD')
    .replace(/\p{Diacritic}/gu, '')
    .toUpperCase()
    .replace(/[^A-Z0-9]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
}

const COUNTRY_LABEL_BY_CODE = new Map<string, string>()
const COUNTRY_CODE_BY_NORMALIZED_LABEL = new Map<string, string>()

for (const option of COUNTRY_OPTIONS) {
  COUNTRY_LABEL_BY_CODE.set(option.code, option.label)
  COUNTRY_CODE_BY_NORMALIZED_LABEL.set(normalizeValue(option.label), option.code)
}

const ALT_LABEL_TO_CODE: Record<string, string> = {
  USA: 'US',
  UNITEDSTATESOFAMERICA: 'US',
  UNITEDSTATES: 'US',
  UNITEDKINGDOM: 'GB',
  GREATBRITAIN: 'GB',
  ENGLAND: 'GB',
  SCOTLAND: 'GB',
  WALES: 'GB',
  RUSSIA: 'RU',
  RUSSIANFEDERATION: 'RU',
  SOUTHKOREA: 'KR',
  NORTHKOREA: 'KP',
  LAOPEOPLESDEMOCRATICREPUBLIC: 'LA',
  BOLIVIAPLURINATIONALSTATEOF: 'BO',
  VENEZUELABOLIVARIANREPUBLICOF: 'VE',
  IRANISLAMICREPUBLICOF: 'IR',
  SYRIANARABREPUBLIC: 'SY',
  REPUBLICOFKOREA: 'KR',
  DEMOCRATICPEOPLESREPUBLICOFKOREA: 'KP',
  REPUBLICOFTHECONGO: 'CG',
  DEMOCRATICREPUBLICOFTHECONGO: 'CD',
  COTEDIVOIRE: 'CI',
  IVORYCOAST: 'CI',
  SWAZILAND: 'SZ',
  BAHAMAS: 'BS',
  GAMBIA: 'GM',
  CABOVERDE: 'CV',
  CAPEVERDE: 'CV',
  MYANMARBURMA: 'MM',
  BURMA: 'MM',
  HONGKONG: 'HK',
  MACAU: 'MO',
  MACAO: 'MO',
  HONGKONGSAR: 'HK',
  MACAOSAR: 'MO',
  TAIWANPROVINCEOFCHINA: 'TW',
  TAIWAN: 'TW',
  KOSOVO: 'XK',
  CZECHREPUBLIC: 'CZ',
  EASTTIMOR: 'TL',
  FEDERATEDSTATESOFMICRONESIA: 'FM',
  STATEOFPALESTINE: 'PS',
  PALESTINIANTERRITORIES: 'PS',
  THEBAHAMAS: 'BS',
  THEGAMBIA: 'GM',
  THENETHERLANDS: 'NL',
  UNITEDKINGDOMOFGREATBRITAINANDNORTHERNIRELAND: 'GB',
  SAOTOMEANDPRINCIPE: 'ST',
  SAOTOMEPRINCIPE: 'ST',
  UNITEDREPUBLICOFTANZANIA: 'TZ',
  REPUBLICOFMOLDOVA: 'MD',
  REPUBLICOFTHEMARSHALLISLANDS: 'MH',
  BRUNEIDARUSSALAM: 'BN',
  VIETNAM: 'VN',
  HOLYSEE: 'VA',
  LAOPDR: 'LA',
  KOREASOUTH: 'KR',
  KOREANORTH: 'KP',
  DEMOCRATICREPUBLICOFCONGO: 'CD',
  REPUBLICOFCONGO: 'CG',
  CONGOBRAZZAVILLE: 'CG',
  CONGOKINSHASA: 'CD',
  DRCONGO: 'CD',
  STKITTSANDNEVIS: 'KN',
  STLUCIA: 'LC',
  STVINCENTANDTHEGRENADINES: 'VC',
  TRINIDADTOBAGO: 'TT',
  ANTIGUABARBUDA: 'AG',
  MACEDONIA: 'MK',
  BOSNIAHERZEGOVINA: 'BA',
  UAE: 'AE',
  MICRONESIAFEDERATEDSTATESOF: 'FM',
}

export function getCountryCode(value: string | null | undefined): string | null {
  if (!value) return null
  const trimmed = value.trim()
  if (!trimmed) return null
  const upper = trimmed.toUpperCase()
  if (/^[A-Z]{2}$/.test(upper) && COUNTRY_LABEL_BY_CODE.has(upper)) {
    return upper
  }
  const normalized = normalizeValue(trimmed)
  const fromNormalized = COUNTRY_CODE_BY_NORMALIZED_LABEL.get(normalized)
  if (fromNormalized) return fromNormalized
  const fallback = ALT_LABEL_TO_CODE[normalized.replace(/\s+/g, '')]
  if (fallback) return fallback
  return null
}

export function getCountryLabel(value: string | null | undefined): string | null {
  const code = getCountryCode(value)
  if (!code) return null
  return COUNTRY_LABEL_BY_CODE.get(code) ?? null
}
